apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy_name | default "deploy01" }}
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      tier: frontend
      app: guestbook
  template:
    metadata:
      labels:
        tier: frontend
        app: guestbook
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.nginx_version }}

