apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
  labels:
    helm.sh/hook: pre-install
{{- include "deploy.labels" . | nindent 4 }}
data:
  player_initial_lives: "3"
  score: "5000"
  name: "John"
